// CharacterLayout.js

export const CharacterLayout = [
  {
    id: "judge",
    refKey: "judgeRef",
    position: [0, 2, -18],
    rotation: [0, Math.PI, 0],
    colorTorso: "#222",
    emotion: "angry",
    sitting: true,
    lookAt: "witness",
  },
  {
    id: "witness",
    refKey: "witnessRef",
    position: [-10, 1.1, -15],
    rotation: [0, Math.PI, 0],
    colorTorso: "#ffd700",
    sitting: true,
    lookAt: "judge",
  },
  {
    id: "plaintiff_1",
    position: [-6.5, 0, -3.5],
    colorTorso: "#1e90ff",
    sitting: true,
    lookAt: "judge",
  },
  {
    id: "plaintiff_2",
    position: [-3.5, 0, -3.5],
    colorTorso: "#1e90ff",
    sitting: true,
    lookAt: "judge",
  },
  {
    id: "defense_1",
    position: [3.5, 0, -3.5],
    colorTorso: "#32cd32",
    sitting: true,
    lookAt: "judge",
  },
  {
    id: "defense_2",
    position: [6.5, 0, -3.5],
    colorTorso: "#32cd32",
    sitting: true,
    lookAt: "judge",
  },
  {
    id: "stenographer",
    position: [-17.5, 0, -8],
    rotation: [0, -Math.PI / 2, 0],
    colorTorso: "#9932cc",
    sitting: true,
    lookAt: "judge",
  },
  ...Array.from({ length: 6 }).map((_, i) => ({
    id: `jury_${i + 1}`,
    position: [18, 0, -13 + i * 1.3],
    rotation: [0, Math.PI / 2, 0],
    colorTorso: "#8b4513",
    sitting: true,
    lookAt: "judge",
  })),
];
